#! /bin/bash
set -e

app_name=$1
repository=$2

if [[ $app_name && $repository ]]; then
    if [ -f "/tmp/${app_name}_last_success.txt" ];then
        tag=$(cat /tmp/${app_name}_last_success.txt | awk '{print $1}')
        echo "前一个版本tag为："${tag}
        docker rmi -f ${repository}:${tag}
        echo "清理老的容器镜像成功"
    fi
fi