version: '3'

services:
  mongodb:
    image: mongo:3.4.1
    volumes:
      - './data/db:/data/db'
    networks:
      - easy-mock
    restart: always

  # redis:
  #   image: redis:4.0.6
  #   command: redis-server --appendonly yes
  #   volumes:
  #     # ./data/redis redis 数据文件存放地址，根据需要修改为本地地址
  #     - './data/redis:/data'
  #   networks:
  #     - easy-mock
  #   restart: always

  web:
    image: easymock/easymock:1.6.0
    command: /bin/bash -c "npm start"
    ports:
      - 7300:7300
    volumes:
      # 日志地址，根据需要修改为本地地址
      - './logs:/home/easy-mock/easy-mock/logs'
      # 配置地址，请使用本地配置地址替换
      - './production.json:/home/easy-mock/easy-mock/config/production.json'
    networks:
      - easy-mock
    restart: always

networks:
  easy-mock: