version: '3'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test
    restart: always
#    tty: true
    volumes:
      - ./:/var/www/data
    networks:
      - test-net

networks:
  test-net:
    driver: bridge
