version: '3'

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - dev-net

networks:
  dev-net:
    driver: bridge

    

    