version: '3'

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - dev-net
    volumes:
      - ../data:/var/wwwroot
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  dev-net:
    driver: bridge

    

    