version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - 49000:8080
      - 50000:50000
    # uncomment for docker in docker
    #privileged: true
    user: root
    volumes:
        # enable persistent volume (warning: make sure that the local jenkins_home folder is created)
        - /data/apps/jenkins/jenkins_home:/var/jenkins_home
        - /root/.ssh:/root/.ssh
        # mount docker sock and binary for docker in docker (only works on linux)
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - /usr/local/jdk1.8.0_211:/usr/local/jdk1.8.0_211
        - /usr/local/maven-3.6.2:/usr/local/maven-3.6.2
        - /root/.m2:/root/.m2