version: '2'
services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins-blueocea
    restart: unless-stopped
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - 49001:8080
      - 50000:50000
    # uncomment for docker in docker
    #privileged: true
    user: root
    volumes:
        # enable persistent volume (warning: make sure that the local jenkins_home folder is created)
        - /data/apps/jenkins/jenkins_home:/var/jenkins_home
        # mount docker sock and binary for docker in docker (only works on linux)
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - /usr/local/jdk1.8.0_162:/usr/local/jdk1.8.0_162
        - /usr/local/apache-maven-3.6.0:/usr/local/apache-maven-3.6.0
        - /root/.m2:/root/.m2