version: '3'
services:
  mysql:
    image: mysql:5.7.21
    container_name: mysql
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=20M',
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: ok
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
