version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=654321
    ports:
      - "20000:27017"
    restart: always
    volumes:
      - ./data:/data/db
      - ./log:/var/log/mongodb
      - ./config:/etc/mongo
