version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=654321
    ports:
      - "27017:27017"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          memory: 512M
    volumes:
      - ./data:/data/db
      - ./log:/var/log/mongodb
      - ./config:/etc/mongo
    networks:
      - db-net

networks:
  db-net:
    driver: bridge
